// TODO: CREATE VPC WITH NAT GATEWAY FOR CONNECTIVITY TO WHATSAPP
// TODO: CREATE SUBNETS IN VPC
// TODO: CREATE ROUTING TABLE FOR CONNECTIVITY BETWEEN SUBNETS
// TODO: CREATE VPC ENDPOINT FOR CLOUDWATCH LOGS, S3, ECR (API AND DKR)
// TODO: DISABLE PUBLIC IP'S FOR TASKS
